language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo locale-gen fr_FR fr_FR.UTF-8
  - locale -a  
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "yes\nyes\nno\nyes\n" | pecl install pecl_http
  - composer self-update
  - mkdir test
  - cd test
  - composer init --no-interaction --stability=dev
  - composer require "photon/photon:dev-refactor/m2conn"
  
script: php vendor/photon/photon/src/photon.php selftest

matrix:
  fast_finish: true
